token:
  main:
#"EAAPEZCteQaEsBAIHU3zcMhrmMN2zbAEN214E7qPV4HTZA1hyEZC5FlFAaHhyxwEdbZA0Bia4h7Hyq6oLpvJZAbucy2Q9bppcc335Ssyx0QfeFmjF8QkKoR0z7q4PbJCnyiJfDucLQi5ZC0QcYgwFnrBIHyiGGOIUTWRw72vwqJBLCzTwd6bvOD"
    "1061023747434571|yeb6YZ18c8Gt1t4OxJvH_RfNLcg"  
  test:
    "1061023747434571|yeb6YZ18c8Gt1t4OxJvH_RfNLcg"  
  verify_webhook:
    'TESTINGTOKEN'
app_id:
  '1061023747434571'
admins: # should be list of admins or move this somewhere else (db?)
  '2648811858479034'
sql:
  rose:
    full_address:
      "mysql://kgacek:{pass}@kgacek.mysql.pythonanywhere-services.com/kgacek$roza?charset=utf8"
log:
  '/home/kgacek/app_logs/app.log'

inputs:
  main:
    'input_data.yaml'
  test:
    'input_test.yaml'
  descriptions:
    'patrons.yaml'
reminder_offset:
  10
